codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 analyze -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]

database:
  before_script:
    - export PYTHONPATH="${PYTHONPATH}:/builds/irmdataprocess/MIA2/src/modules"
    - export PYTHONIOENCODING=utf-8
    - PYTHONUNBUFFERED=0
    - apk update
    - apk upgrade
    - apk add python3 python3-dev python3-tkinter python3-idle boost-python3 python3-dbg uwsgi-python3 python3-wininst libpeas-python3 py-sip
    - pip3 install --upgrade pip
    - pip3 install sqlalchemy
    - ls
    - wget https://pypi.python.org/packages/cc/eb/f2e115d21abec6d86b2af0b7fa6f71439767d0a91cb393607e4f72998b0a/PyQt5-5.6-cp35-none-win32.whl
    - ls
    - pip3 install PyQt5-5.6-cp35-none-win32.whl

  script:
    - python3 -u tests.py

