codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 analyze -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]

database:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - docker info
    - export PYTHONPATH="${PYTHONPATH}:/builds/irmdataprocess/MIA2/src/modules"
    - export PYTHONIOENCODING=utf-8
    - PYTHONUNBUFFERED=0
    - apk update
    - apk upgrade
    - apk add git rsync openssh python3 python3-dev build-base
    - pip3 install --upgrade pip
    - pip3 install docker-compose
    - pip3 install sqlalchemy
    #- pip3 install pyqt5-installer
    #- find / -iname PyQt5
    #- pip3 install PyQt5
    - docker pull pypi/pyqt5

  script:
    - python3 -u tests.py

