repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks: # general hooks
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: name-tests-test
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks: # code formatter
    -   id: black
        language: python
        args: ["--line-length=79"]

-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks: # documentation checker
    -   id: interrogate
        args: [--fail-under=80, -vv]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks: # imports sorting
    -   id: isort
        name: isort (python)
