environment:

  matrix:
    - PYTHON: "C:\\Python36"
#    - PYTHON: "C:\\Python37"
#    - PYTHON: "C:\\Python38"
# python3.8 and PyQt5 doesn't seem to be fully compatible yet
# pip install PyQt5==5.9.2
# ERROR: Could not find a version that satisfies the requirement PyQt5==5.9.2 (from versions: 5.10.1, 5.11.2, 5.11.3, 5.12, 5.12.1, 5.12.2, 5.12.3, 5.13.0, 5.13.1, 5.13.2, 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1)
# and
# pip install PyQt5==5.10.1
# Collecting PyQt5==5.10.1
# Downloading PyQt5-5.10.1-5.10.1-cp35.cp36.cp37.cp38-none-win32.whl (68.6 MB)
# ERROR: Could not find a version that satisfies the requirement sip<4.20,>=4.19.4 (from PyQt5==5.10.1) (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0, 5.4.0)

build: off

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade -vv setuptools"
  - "pip install --upgrade cython"
  - "pip install numpy"
  - "pip install freetype-py"
  - "pip install pypng"
  - "pip install --upgrade pywavelets"
  - "pip install pypiwin32"
  - "python setup.py install"
  - "git lfs install"
  - "git lfs pull"
  - "echo y | pip uninstall PyQt5"
  - "echo y | pip uninstall PyQt5-sip"
  - "echo y | pip uninstall SIP"
  - "pip install PyQt5==5.9.2"
  - "git clone --depth=50 --branch=master https://github.com/populse/populse_db.git C:\\projects\\populse-db"
  - "cd C:\\projects\\populse-db"
  - "pip install -e .[postgres]"
  - "cd .."
  - "git clone --depth=50 --branch=master https://github.com/populse/soma-base.git C:\\projects\\soma-base"
  - "cd populse-mia"
  - "SET PYTHONPATH=C:\\projects\\populse-mia\\python\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\soma-base\\python\\;%PYTHONPATH%"

test_script:
  - "python --version"
  - "python .\\python\\populse_mia\\test.py -v"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
