environment:
  
  matrix:

    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade cython"
  - "pip install numpy"
  - "python setup.py install"
  - "pip install --upgrade --force-reinstall pyqt5"
  - "cd .."
  - "git clone --depth=50 --branch=master https://github.com/populse/populse_db.git"
  - "cd populse_sandbox"
  - "SET PYTHONPATH=C:\\projects\\populse-db\\python\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-sandbox\\python\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-sandbox\\python\\populse-mia\\src\\modules\\PipelineManager\\Processes\\;%PYTHONPATH%"
  - "export DISPLAY=:99.0"
  - "sleep 3"

test_script:
  - "python .\\python\\populse_mia\\src\\scripts\\test.py"
