environment:
  
  matrix:

    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build_script:
  - "SET PATH=C:\\Program Files\\PostgreSQL\\9.6\\bin\\;%PATH%"
  - psql -c "create database populse_db_tests;" -U postgres

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --upgrade cython"
  - "python setup.py install"

test_script:
  - "python ./python/populse_mia/src/scripts/test.py"
