environment:
  
  matrix:

    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --upgrade cython"
  - "python setup.py install"

test_script:
  - "python .\\python\\populse_mia\\src\\scripts\\test.py"
