environment:

  matrix:
    - PYTHON: "C:\\Python37"
    #- PYTHON: "C:\\Python38"
    #- PYTHON: "C:\\Python39"

build: off

install:
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade -vv setuptools"
  - "pip install --upgrade cython"
  - "pip install numpy"
  - "pip install freetype-py"
  - "pip install pypng"
  - "pip install --upgrade pywavelets"
  - "pip install pypiwin32"
  - "pip install \"scipy<1.5\""
  - "pip install coverage"
  - "pip install codecov"
  - "python setup.py install"
  - "git lfs install"
  - "git lfs pull"
  - "echo y | pip uninstall PyQt5"
  - "echo y | pip uninstall PyQt5-sip"
  - "pip install \"PyQt5==5.9.2\""
  - "pip uninstall -y capsul soma-base populse_db"
  - "git clone --depth=50 --branch=2.0 https://github.com/populse/populse_db.git C:\\projects\\populse_db"
  - "cd C:\\projects\\populse_db"
  - "pip install -e .[postgres]"
  - "cd .."
  - "git clone --depth=50 --branch=master https://github.com/populse/soma-base.git C:\\projects\\soma-base"
  - "git clone --depth=50 --branch=master https://github.com/populse/capsul.git C:\\projects\\capsul"
  - "cd populse-mia"
  - "SET PYTHONPATH=C:\\projects\\populse-mia\\python;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\soma-base\\python;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\capsul;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse_db\\python;%PYTHONPATH%"

test_script:
  - "python --version"
  - "python .\\python\\populse_mia\\test.py -v"
  - "coverage run .\\python\\populse_mia\\test.py -v"

after_test:
  - "codecov"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
