environment:
  
  matrix:

#   - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.0"

build: off

init:

  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade cython"
  - "pip install numpy"
  - "python setup.py install"
  - "pip install --upgrade --force-reinstall pyqt5"
  - "git clone --depth=50 --branch=master https://github.com/populse/populse_db.git C:\\projects\\populse-db"
  - "SET PYTHONPATH=C:\\projects\\populse-db\\python\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-sandbox-rrm4w\\python\\populse_mia\\src\\scripts\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-sandbox-rrm4w\\python\\populse_mia\\src\\modules\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-sandbox-rrm4w\\python\\populse_mia\\src\\modules\\PipelineManager\\Processes\\;%PYTHONPATH%"

test_script:
  - "python --version"
  - "python .\\python\\populse_mia\\src\\scripts\\test.py"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
