environment:

  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

build: off

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade -vv setuptools"
  - "pip install --upgrade cython"
  - "pip install numpy"
  - "pip install freetype-py"
  - "pip install pypng"
  - "pip install --upgrade pywavelets"
  - "pip install pypiwin32"
  # Temporary fix for the issue with kiwisolver 1.2.0 and MarkupSafe 2.0.0a1 which are automatically installed as a required library when installing populse_mia (python3 setup.py install, below) and that crashs with python 3.5 - 16/04/2020
  - IF "%PYTHON%"=="C:\Python35" pip3 install kiwisolver==1.1.0  MarkupSafe==1.1.1
  - "pip install scipy<1.5"
  - "python setup.py install"
  - "git lfs install"
  - "git lfs pull"
  - "echo y | pip uninstall PyQt5"
  - "pip install PyQt5==5.9.2"
  - "pip uninstall -y capsul soma-base populse_db"
  - "git clone --depth=50 --branch=2.0 https://github.com/populse/populse_db.git C:\\projects\\populse_db"
  - "cd C:\\projects\\populse_db"
  - "pip install -e .[postgres]"
  #- "pip install --force-reinstall lark-parser==0.6.7"
  - "cd .."
  - "git clone --depth=50 --branch=master https://github.com/populse/soma-base.git C:\\projects\\soma-base"
  - "git clone --depth=50 --branch=master https://github.com/populse/capsul.git C:\\projects\\capsul"
  - "cd populse-mia"
  - "SET PYTHONPATH=C:\\projects\\populse-mia\\python;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\soma-base\\python;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\capsul;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse_db\\python;%PYTHONPATH%"

test_script:
  - "python --version"
  - "python .\\python\\populse_mia\\test.py -v"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
