environment:

  matrix:

#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      PYTHON: "C:\\Python37"
#      APPVEYOR_RDP_PASSWORD:

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "$HOME/venv3.7"
      APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdDYk1yZyk/W/2UtL1oBEDzX9Mk6YUXJKS3gTrZaK+ScAzPUkm7UlXwwpzSYZjKIkYzpi3WKSRKuDc7VRVk43hIhmwaIzcmpHAXtbgxAGRYembgz+kLDGtkhlP4i8n5GfNWvkkfbS0pu2w2dZQB7EGFFtopfvzBokKltjAYOnP89GCAo4MTfx6kmv1tpm1SDbCAGHJPuN+81B47+v0uGw3KG+AX+1ezPv1MCBQl5V2J4MI6vomyaHz6/UNBZ6rpsrZBYRljwWbyH5E5fqLdep/kO9sEuiXxTrCTLnUPSrR0+h0f8HlgWCaqxO+OUyDoQMI3xsUn4sMpoASi8jkDgd51vGbzkQHyjy2hYzjs47GAvLLtGfTJYQBVcfXEoZaKQUJhqjR7TUdY4bSBOxIPR9qlA9fLFwlQsC3++0m4roM/0SyoDVTz0I6lp1TsYRMKxEJSM90ewCAK8UnN6gEqmOz5ezOFpVsnpz4bZ7vCGaJa/6ODfOhEvl5bFUK40+GxSk= otavio@otavio-UX430UAR

#    - APPVEYOR_BUILD_WORKER_IMAGE: macos
#      PYTHON: "~/venv3.7"
#      APPVEYOR_SSH_KEY:

build: off

install:
  - cmd: echo "     ** windows build **"
  - sh: if [[ $(uname -s) == Linux ]]; then echo "     ** linux build **"; fi
  - sh: if [[ $(uname -s) == Darwin ]]; then echo "     ** macos build **"; fi

#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

  - cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - sh: export PATH=~/venv3.7/bin:~/venv3.7/lib:$PATH
  
  - python --version
  - python -m pip install pip --upgrade
  - pip -V
  - pip install setuptools --upgrade
  - pip install cython --upgrade
  - pip install numpy
  - pip install freetype-py
  - pip install pypng
  - pip install pywavelets --upgrade

  - cmd: pip install pypiwin32

  - cmd: "pip install \"scipy<1.5\""
  - sh: pip3 install 'scipy<1.5'

  - pip install codecov
  - pip install --upgrade --force-reinstall pyparsing==2.4.7
# This is a patch to avoid the "AttributeError: 'PathMetadata' object has no attribute 'isdir'" observed since pip-22.0.2 (see for example UT for commit 50187200b6):
  - pip install capsul soma-workflow
  - python setup.py install
  - git lfs install
  - git lfs pull
  - echo y | pip uninstall PyQt5
  - echo y | pip uninstall PyQt5-sip

  - cmd: "pip install \"PyQt5==5.9.2\""
  - sh: pip3 install 'PyQt5==5.9.2'

  - pip uninstall -y populse_db soma-base soma-workflow capsul

  - cmd: git clone --depth=50 --branch=master https://github.com/populse/populse_db.git C:\\projects\\populse_db
  - sh: if [[ $(uname -s) == Linux ]]; then git clone --depth=50 --branch=master https://github.com/populse/populse_db.git /home/appveyor/projects/populse_db; fi
  - sh: if [[ $(uname -s) == Darwin ]]; then git clone --depth=50 --branch=master https://github.com/populse/populse_db.git /Users/appveyor/projects/populse_db; fi

  - cmd: cd C:\\projects\\populse_db
  - sh: if [[ $(uname -s) == Linux ]]; then cd /home/appveyor/projects/populse_db; fi
  - sh: if [[ $(uname -s) == Darwin ]]; then cd /Users/appveyor/projects/populse_db; fi

  - pip install -e .[postgres]
  - cd ..

  - cmd: git clone --depth=50 --branch=master https://github.com/populse/soma-base.git C:\\projects\\soma-base
  - sh: if [[ $(uname -s) == Linux ]]; then git clone --depth=50 --branch=master https://github.com/populse/soma-base.git /home/appveyor/projects/soma-base; fi
  - sh: if [[ $(uname -s) == Darwin ]]; then git clone --depth=50 --branch=master https://github.com/populse/soma-base.git /Users/appveyor/projects/soma-base; fi

  - cmd: git clone --depth=50 --branch=master https://github.com/populse/soma-workflow.git C:\\projects\\soma-workflow
  - sh: if [[ $(uname -s) == Linux ]]; then git clone --depth=50 --branch=master https://github.com/populse/soma-workflow.git /home/appveyor/projects/soma-workflow; fi
  - sh: if [[ $(uname -s) == Darwin ]]; then git clone --depth=50 --branch=master https://github.com/populse/soma-workflow.git /Users/appveyor/projects/soma-workflow; fi

  - cmd: git clone --depth=50 --branch=master https://github.com/populse/capsul.git C:\\projects\\capsul
  - sh: if [[ $(uname -s) == Linux ]]; then git clone --depth=50 --branch=master https://github.com/populse/capsul.git /home/appveyor/projects/capsul; fi
  - sh: if [[ $(uname -s) == Darwin ]]; then git clone --depth=50 --branch=master https://github.com/populse/capsul.git /Users/appveyor/projects/capsul; fi

  - cd populse-mia

  - sh: if [[ $(uname -s) == Linux ]]; then Xvfb & fi
  - sh: if [[ $(uname -s) == Linux ]]; then sleep 3; fi # give xvfb some time to start
  
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

test_script:
  - cmd: python .\\python\\populse_mia\\test.py -v

  - sh: if [[ $(uname -s) == Darwin ]]; then python3 ./python/populse_mia/test.py -v; fi

  - sh: if [[ $(uname -s) == Linux ]]; then if [ -z $XDG_RUNTIME_DIR ]; then export XDG_RUNTIME_DIR="/tmp/runtime-$(id -un)"; if [ ! -d "/tmp/runtime-$(id -un)" ]; then mkdir "/tmp/runtime-$(id -un)"; chmod 0700 "/tmp/runtime-$(id -un)"; fi; fi; fi
  - sh: if [[ $(uname -s) == Linux ]]; then xvfb-run python3 ./python/populse_mia/test.py -v; fi
  - sh: if [[ $(uname -s) == Linux ]]; then xvfb-run coverage run ./python/populse_mia/test.py -v; fi

after_test:
  - sh: if [[ $(uname -s) == Linux ]]; then codecov; fi

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
