environment:
  
  matrix:

    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade cython"
  - "pip install numpy"
  - "python setup.py install"
  - "pip install --upgrade --force-reinstall pyqt5"
  - "cd .."
  - "git clone --depth=50 --branch=master https://github.com/populse/populse_db.git"
  - "SET PYTHONPATH=C:\\projects\\populse_db\\python\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-sandbox-rrm4w\\python\\;%PYTHONPATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-sandbox-rrm4w\\python\\populse_mia\\src\\modules\\PipelineManager\\Processes\\;%PYTHONPATH%"

test_script:
  - "python C:\\projects\\populse-sandbox-rrm4w\\python\\populse_mia\\src\\scripts\\test.py"
