[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
atomic = true
profile = "black"
line_length = 79
skip_gitignore = true
# known_first_party = ['python']

[tool.coverage.run]
omit = [
    "python/populse_mia/user_interface/data_viewer/anatomist_2/*",
    "python/populse_mia/user_interface/data_viewer/anatomist/*"
]
