"""Configuration file for the Sphinx documentation builder."""

# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import sys
from pathlib import Path

# Resolve the root directory (4 levels up from __file__)
root = Path(__file__).resolve().parents[3]

# Optional sibling packages: (folder_name, relative_subpath_to_add)
SIBLING_PACKAGES = [
    ("populse_db", "populse_db/python"),
    ("mia_processes", "mia_processes"),
    ("capsul", "capsul"),
    ("soma-base", "soma-base/python"),
    ("soma-workflow", "soma-workflow/python"),
]

if (root / "populse_mia").is_dir():
    print("\nGenerating sphinx documentation in developer mode ...")
    print(f" - Adding {Path('../..').resolve()} to the sys.path ...")
    sys.path.insert(0, str(Path("../..").resolve()))

    for folder, subpath in SIBLING_PACKAGES:
        path = Path("../../..") / subpath
        if (root / folder).is_dir():
            print(f" - Adding {path.resolve()} to the sys.path ...")
            sys.path.insert(1, str(path.resolve()))

import populse_mia

# -- project information -----------------------------------------------------

project = "populse_mia"
copyright = "2022, populse"
author = "populse"

# The short X.Y version
version = ""
# The full version, including alpha/beta/rc tags
release = populse_mia.__version__


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    "sphinx.ext.napoleon",
    "myst_parser",
]

try:
    import sphinxcontrib.mermaid

    # flake8 ignore F401
    extensions.append("sphinxcontrib.mermaid")

except ImportError:
    # oh well... no schemas then.
    print(
        "sphinxcontrib.mermaid is not present on your system. Schemas will "
        "not be rendered in docs. You probably should consider installing "
        "it using:\n\n"
        "pip install sphinxcontrib.mermaid\n",
        file=sys.stderr,
    )

autosummary_generate = True
autosummary_imported_members = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# language = None
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "**.#*",
    "**/*~",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "haiku"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# The following html_static_path = is commented to fix the warning:
# copying static files... WARNING: html_static_path entry '/home/econdami/
# Git_Projects/populse_mia/docs/source/_static' does not exist
# html_static_path = ['_static']


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "populse_miadoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "populse_mia.tex",
        "populse\\_mia Documentation",
        "populse",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "populse_mia", "populse_mia Documentation", [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "populse_mia",
        "populse_mia Documentation",
        author,
        "populse_mia",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------


autodoc_default_options = {
    "members": True,
    "private-members": True,
    "undoc-members": True,
    "special-members": "__init__",
    "member-order": "bysource",
    "show-inheritance": True,
    "imported-members": False,
}


# -- Intersphinx configuration -----------------------------------------------

extlinks = {
    "somabase": ("https://populse.github.io/soma-base/%s", "somabase "),
    "somaworkflow": (
        "https://populse.github.io/soma-workflow/%s",
        "somaworkflow ",
    ),
    "casadistro": (
        "https://brainvisa.github.io/casa-distro/%s",
        "casadistro ",
    ),
}


pyversion = "%d.%d" % sys.version_info[:2]

intersphinx_mapping = {
    "somabase": ("https://populse.github.io/soma-base", None),
    "somaworkflow": ("https://populse.github.io/soma-workflow", None),
    "python": ("https://docs.python.org/%s" % pyversion, None),
    "traits": ("https://docs.enthought.com/traits", None),
}


# -- mermaid configuration ---------------------------------------------------

mermaid_output_format = "raw"
