auto_save: 'no'
background_color: ''
chain_cursors: 'no'
clinical_mode: 'no'
matlab: /home/econdami/MATLAB/R2018b/bin/matlab
matlab_standalone: ''
max_projects: 5.0
mia_path: /home/econdami/Git_Projects/populse_mia
mri_conv_path: /home/econdami/Git_Projects/mri_conv/MRIFileManager/MRIManager.jar
name: MIA
nb_slices_max: '10'
opened_projects: []
projects_save_path: /home/econdami/Git_Projects/populse_mia/projects
show_all_slices: 'no'
spm: /home/econdami/SPM/spm12
text_color: ''
thumbnail_tag: SequenceName
use_matlab: 'yes'
use_spm: 'yes'
use_spm_standalone: 'no'
