auto_save: 'no'
background_color: ''
chain_cursors: 'no'
clinical_mode: 'no'
matlab: /usr/local/MATLAB/R2018b/bin/matlab
matlab_standalone: ''
max_projects: 5.0
mia_path: /home/gin-talbot-pc/populse_mia_dev
mri_conv_path: /home/gin-talbot-pc/.populse_mia/MRIFileManager/MRIManager.jar
name: MIA
nb_slices_max: '10'
opened_projects: []
projects_save_path: /home/gin-talbot-pc/populse_mia_dev/projects
show_all_slices: 'no'
spm: /home/gin-talbot-pc/Apps/spm12
text_color: ''
thumbnail_tag: SequenceName
use_matlab: 'yes'
use_spm: 'yes'
use_spm_standalone: 'no'
