auto_save: 'no'
background_color: ''
chain_cursors: 'yes'
default_tags:
- FileName
- PatientName
- AcquisitionDate
name: MIA2
nb_slices_max: '10'
paths:
  data: C:\Users\omonti\Documents\DataIRM\NifTI\testNifti\
  modules: modules
  projects: ..\data
show_all_slices: 'no'
text_color: ''
thumbnail_tag: SequenceName
