Packages:
  Processes:
    Addition: process_enabled
    FSL_Smooth: process_enabled
    FSL_Smooth_Real: process_enabled
    SPM_Coregister: process_enabled
    SPM_NewSegment: process_enabled
    SPM_Normalize: process_enabled
    SPM_Realign: process_enabled
    SPM_Smooth: process_enabled
    Substraction: process_enabled
  nipype:
    interfaces:
      spm:
        Analyze2nii: process_enabled
        ApplyInverseDeformation: process_enabled
        ApplyTransform: process_enabled
        CalcCoregAffine: process_enabled
        Coregister: process_enabled
        CreateWarped: process_enabled
        DARTEL: process_enabled
        DARTELNorm2MNI: process_enabled
        DicomImport: process_enabled
        EstimateContrast: process_enabled
        EstimateModel: process_enabled
        FieldMap: process_enabled
        Info: process_enabled
        Level1Design: process_enabled
        MultipleRegressionDesign: process_enabled
        NewSegment: process_enabled
        Normalize: process_enabled
        Normalize12: process_enabled
        OneSampleTTestDesign: process_enabled
        PairedTTestDesign: process_enabled
        Realign: process_enabled
        Reslice: process_enabled
        ResliceToReference: process_enabled
        SPMCommand: process_enabled
        Segment: process_enabled
        SliceTiming: process_enabled
        Smooth: process_enabled
        Threshold: process_enabled
        TwoSampleTTestDesign: process_enabled
        VBMSegment: process_enabled
Paths:
- /home/david/MIA2/src/modules/PipelineManager
- /home/david/MIA2/src/modules/PipelineManager
- /home/david/MIA2/src/modules/PipelineManager
- /home/david/MIA2/src/modules/PipelineManager
